### ISSUE TITLE
Facebook profile picture

### ISSUE THREAD

**Issue by ArielS1** [J-Priebe/react-native-facebook-firebase#1]
Hi,

I want to modify the app's logic, for examlpe:
Retrieve logged user's pictures instead of profile picture.

The problem is that i couldn't understand in the code from where does the profile photo url comes from?
I would like to modify that request to a different method in Graph API, but i just can't understand where is the original Graph call?

Or maybe the profile picture is something that comes built-in with the fbsdk that is included in your project?

I also didn't understand what does Splash do.

Thanks

**Comment by J-Priebe** [comment]
Hi,

currentUser.photoURL is actually a firebase prop - it is not part of fbsdk. However, you could use the auth token you get with fbsdk to authenticate other API calls to Facebook.

Splash is necessary because as far as I know Flux/Redux doesn't allow you to dynamically change the root of your application. Splash is the first route, and then you are taken to Login or Home depending on whether you are logged in or not.

Thank you for opening an issue, the README could use some updates :)

James

**Comment by ArielS1** [comment]
Let me understand, does users that authenticate with facebook on firebase, firebase automatically saves the profile photo URL on the user's props?
Is there anything else interesting that he saves?

**Comment by J-Priebe** [comment]
Correct. By authorizing sign-in with facebook, firebase needs permissions for your basic profile, which includes your profile picture. I think just name and profile picture are provided by default. For additional permissions (user's birthday, likes, etc.) you would have to use the LoginManager, which is also part of fbsdk:
https://github.com/facebook/react-native-fbsdk#requesting-additional-permissions-with-login-manager
